from build_montage import (
    DEFAULT_MAX_DURATION_SECONDS,
    DEFAULT_MAX_EVENTS,
    DEFAULT_PER_EVENT_DURATION_SECONDS,
    SOURCE_WINDOW_AFTER_SECONDS,
    SOURCE_WINDOW_BEFORE_SECONDS,
)


def test_frozen_highlight_policy_is_five_complete_thirty_second_events():
    assert DEFAULT_MAX_EVENTS == 5
    assert SOURCE_WINDOW_BEFORE_SECONDS == 15.0
    assert SOURCE_WINDOW_AFTER_SECONDS == 15.0
    assert DEFAULT_MAX_DURATION_SECONDS == 150.0
    assert DEFAULT_PER_EVENT_DURATION_SECONDS == 30.0
    assert DEFAULT_MAX_EVENTS * DEFAULT_PER_EVENT_DURATION_SECONDS == DEFAULT_MAX_DURATION_SECONDS
